services:
  - type: web
    name: chegouai
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://chegouaiapp.com.br
      - key: FRONTEND_URL
        value: https://chegouaiapp.com.br
      - key: WEBHOOK_URL
        value: https://chegouaiapp.com.br
      - key: SUPABASE_URL
        value: https://lgcepuednurxwsandgaf.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnY2VwdWVkbnVyeHdzYW5kZ2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3OTA2NDgsImV4cCI6MjA4OTM2NjY0OH0.4X406qQXrkgVMQlCssoKQUhclII3g7BdqJW2lJTFiYw
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnY2VwdWVkbnVyeHdzYW5kZ2FmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzc5MDY0OCwiZXhwIjoyMDg5MzY2NjQ4fQ.9cFG0_aS2pgtY88SjTaf_FZJjO2s1Lh4APtO6x0BEJE
      - key: PAGARME_API_KEY
        value: sk_11d71b8916714a848d2dafd1bfc893d2
      - key: PAGARME_WEBHOOK_USER
        value: chegouai
      - key: PAGARME_WEBHOOK_PASS
        value: Chegouai2026#
      - key: PAGARME_RECIPIENT_ID_PLATAFORMA
        value: re_cmnrvtft2w1sc0l9ta0brncv2
      - key: PAGARME_TAXA_PIX_PERCENT
        value: "0.99"
      - key: PAGARME_TAXA_CARTAO_PERCENT
        value: "3.99"
      - key: PAGARME_TAXA_ANTECIPACAO_PERCENT
        value: "1.99"
      - key: PAGARME_TAXA_FIXA_CARTAO
        value: "0.70"
      - key: VAPID_PUBLIC_KEY
        value: BIuzKNh95xo8YIIsV8c5vMrnh2A5nmfce-bINM6FZoHCghQ8nS2xvEArwLoXwIRIIzNo8E3OFxsINK9TGQqzI98
      - key: VAPID_PRIVATE_KEY
        value: iMJSPBVi6Z_EREetqC0V4nrtrIlbJ0CKCgxKn-L6Mi8
      - key: VAPID_EMAIL
        value: mailto:helttongalvao@gmail.com
      - key: JWT_SECRET
        value: fa9fcceb8aaf4e48d2a5a6013fad944c01a3cc123664d46adc83f449dd15a770c1b85c536acfbf717f4cd0c0b2b0da6f48ca624770c264f8f8e23de46caa2aeb
